---
title: "lagged_regression"
author: "Juliana Cornett"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## lagged regression for comparing A. catenella counts vs. PSTs

#install packages

```{r}
#install.packages("tseries")
#install.packages("tidyverse")
#install.packages("ggpubr")
#install.packages("astsa")
```

#load libraries

```{r}
library(tseries)
library(tidyverse)
library(ggpubr)
library(astsa)
```

#read in data

```{r}
qpcr <- read.csv("../Data/Alexandrium_qPCR_Results.csv")
pst <- read.csv("../Data/Oyster_PSTs.csv")
count <- read.csv("../Data/Alexandrium_MicroscopeCounts.csv")
```

#format

```{r}
pst$Date <- as.Date(pst$Date, "%m/%d/%Y")
count$Date <- as.Date(count$Date, "%m/%d/%Y")
qpcr$Date <- as.Date(qpcr$Date, "%m/%d/%Y")
qpcr <- subset(qpcr, qpcr$Sample_Type == "Sample")
qpcr <- subset(qpcr, qpcr$Quantity_Corrected >= 63.98)
qpcr_mean <- aggregate(Copies_L_Corrected ~ Date, data = qpcr, FUN = mean)
```

#merge

```{r}
df_list <- list(qpcr_mean, pst, count)
df_merged <- Reduce(function(x,y) merge(x,y, all=TRUE), df_list)
df_merged_elisa <- subset(df_merged, Method == "ELISA")
df_merged_elisa
df_merged_elisa_na <- na.omit(df_merged_elisa)
```

#cross correlation function - ELISA

```{r}
?ccf

#net tow vs. ELISA
ccf(df_merged_elisa$Count_Net, df_merged_elisa$Tox_ug_100g)

#1m vs. ELISA
values_1m_elisa = ccf(df_merged_elisa$Count_1m_L, df_merged_elisa$Tox_ug_100g)
values_1m_elisa

#5m vs. ELISA
ccf(df_merged_elisa$Count_5m_L, df_merged_elisa$Tox_ug_100g)

#qPCR vs. ELISA
values_qpcr_elisa = ccf(df_merged_elisa_na$Copies_L_Corrected, df_merged_elisa_na$Tox_ug_100g)
values_qpcr_elisa
lag2.plot(df_merged_elisa_na$Copies_L_Corrected, df_merged_elisa_na$Tox_ug_100g, 1)

qpcrlag1 = lag(df_merged_elisa_na$Copies_L_Corrected, 1)
summary(lm(Tox_ug_100g~qpcrlag1, data = df_merged_elisa_na))
ggplot(df_merged_elisa_na, aes(x = qpcrlag1, y = Tox_ug_100g)) + geom_point()

#log transformed qpcr
df_merged_elisa_na$log_qpcr <- log(df_merged_elisa_na$Copies_L_Corrected)
ccf(df_merged_elisa_na$log_qpcr, df_merged_elisa_na$Tox_ug_100g)
lag2.plot(df_merged_elisa_na$log_qpcr, df_merged_elisa_na$Tox_ug_100g, 1)

logqpcrlag1 = lag(df_merged_elisa_na$log_qpcr, 1)
summary(lm(Tox_ug_100g~logqpcrlag1, data = df_merged_elisa_na))

lag_qpcr_elisa <- ggplot(df_merged_elisa_na, aes(x = logqpcrlag1, y = Tox_ug_100g)) + geom_point() + 
  stat_poly_line(se = FALSE, size = 2, color = "black") +
  #stat_poly_eq(use_label(c("R2", "p"))) +
  theme_pubr() +
  geom_text(aes(x = 15, y = 240, label = "r^2 == 0.43~~~p == 0.002"), parse = TRUE, color = "black", check_overlap = TRUE) +
  labs(
    x = "Mean log-transformed *A. catenella* qPCR Quantity (Copies/L) at t-1",
    y = "PSTs from ELISA (\u00b5g/100g)") +
  theme(axis.title.x = ggtext::element_markdown(), axis.title.y = ggtext::element_markdown()) 
lag_qpcr_elisa
```

#save as jpeg

```{r}
jpeg("../Figures/FigS4.jpg", width = 8, height = 5, units="in", res=600)
lag_qpcr_elisa
```

#cross correlation function - MBA

#read in data with MBA values paired to other measures <48 hours

```{r}
df_paired <- read.csv("../Data/PST_Pairs_Long_v2.csv")
df_paired_mba <- subset(df_paired, Method == "MBA")
```

#ccf

```{r}
#net tow vs. MBA
ccf(df_paired_mba$Count_Net, df_paired_mba$Tox_ug_100g)

#1m vs. MBA
ccf(df_paired_mba$Count_1m_L, df_paired_mba$Tox_ug_100g)

#5m vs. MBA
ccf(df_paired_mba$Count_5m_L, df_paired_mba$Tox_ug_100g)

#qPCR vs. MBA
ccf(df_paired_mba$Copies_L, df_paired_mba$Tox_ug_100g)

#log qPCR vs. MBA
df_paired_mba$log_qpcr <- log(df_paired_mba$Copies_L)
ccf(df_paired_mba$log_qpcr, df_paired_mba$Tox_ug_100g)
```
