---
title: "nondetects"
author: "Juliana Cornett"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## nondetects

#Table 6 in this paper lists packages/functions in R to use: https://setac.onlinelibrary.wiley.com/doi/10.1002/etc.4046

```{r}
install.packages("AER")
#tobit function fits a tobit model to data
install.packages("censReg")
#censReg function performs tobit regression
install.packages("EnvStats")
#qqPlotCensored produces Q-Q plot for left-censored data
```

#load libraries

```{r}
library(AER)
```

#read in data

```{r}
pst <- read.csv("../Data/PST_Pairs_v2.csv")
pst_counts <- read.csv("../Data/PST_Pairs_Long_v2.csv") 
pst_counts_mba <- subset(pst_counts, Method == "MBA")
```

#TOBIT MODELS

#tobit model for MBA~ELISA

```{r}
tobit_pst = tobit(PST_MBA_ug_100g~PST_ELISA_ug_100g, data = pst, left = 34)
summary(tobit_pst)
```

#tobit model for MBA~1m

```{r}
tobit_1m = tobit(Tox_ug_100g~Count_1m_L, data = pst_counts_mba, left = 34)
summary(tobit_1m)
```

#tobit model for MBA~5m

```{r}
tobit_5m = tobit(Tox_ug_100g~Count_5m_L, data = pst_counts_mba, left = 34)
summary(tobit_5m)
```

#tobit model for MBA~net tow

```{r}
tobit_net = tobit(Tox_ug_100g~Count_Net, data = pst_counts_mba, left = 34)
summary(tobit_net)
```

#tobit model for MBA~qPCR

```{r}
tobit_qpcr = tobit(Tox_ug_100g~Copies_L, data = pst_counts_mba, left = 34)
summary(tobit_qpcr)
```

#tobit model on MBA~logqPCR

```{r}
pst_counts_mba$logqpcr <- log(pst_counts_mba$Copies_L)
tobit_log_qpcr = tobit(Tox_ug_100g~logqpcr, data = pst_counts_mba, left = 34)
summary(tobit_log_qpcr)
```

#IMPUTE NONDETECTS WITH ROS

```{r}
pst_combined <- merge(pst, pst_counts_mba, by = "Pair") 
pst_combined <- select(pst_combined, c("Pair", "PST_ELISA_ug_100g", "Date_ELISA", "PST_MBA_ug_100g", "Date_MBA", "Count_1m_L", "Count_5m_L", "Count_Net", "Copies_L", "logqpcr"))
pst_combined
```

