---
title: "phytoplankton_count_plots"
author: "Juliana Cornett"
date: "2023-08-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#code to generate phytoplankton count plots (Figure 2A, 2B, & 2C in manuscript)

#install packages (ggplot2 & ggpubr for creating figures, patchwork to combine figures)

```{r}
#install.packages("ggplot2")
#install.packages("ggpubr")
#install.packages("patchwork")
```

#load libraries

```{r}
library(ggplot2)
library(ggpubr)
library(patchwork)
```

#read in phytoplankton count data (net tow, 1m, & 5m)

```{r}
phyto_net <- read.csv("../Data/Phytoplankton_NetTow.csv")
phyto_1m <- read.csv("../Data/Phytoplankton_1m.csv")
phyto_5m <- read.csv("../Data/Phytoplankton_5m.csv")
```

#put date in date format for timeseries

```{r}
phyto_net$Date <- as.Date(phyto_net$Date, "%m/%d/%Y")
phyto_1m$Date <- as.Date(phyto_1m$Date, "%m/%d/%Y")
phyto_5m$Date <- as.Date(phyto_5m$Date, "%m/%d/%Y")
```

#net tow plot (A)

```{r}
plot_net <- ggplot(phyto_net, aes(x = Date, y = Alexandrium_spp)) +
  geom_point(size = 5, shape = 21, fill = "#BBEFBE") +
  theme_pubr() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(x = NULL, y = "Alexandrium in Net Tow (count)") +
annotate("text", x=as.Date("2023-05-04"), y=30, label = "A", size = 5) 
plot_net
```

#1m plot (B)

```{r}
plot_1m <- ggplot(phyto_1m, aes(x = Date, y = Alexandrium_spp)) +
  geom_point(size = 5, shape = 21, fill = "#99DEDB") +
  theme_pubr() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(x = NULL, y = "Alexandrium at 1m (cells/L)") +
annotate("text", x=as.Date("2023-05-04"), y=1500, label = "B", size = 5) 
plot_1m
```

#5m plot (C)

```{r}
plot_5m <- ggplot(phyto_5m, aes(x = Date, y = Alexandrium_spp)) +
  geom_point(size = 5, shape = 21, fill = "#AAB8DC") +
  theme_pubr() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  labs(x = NULL, y = "Alexandrium at 5m (cells/L)") +
annotate("text", x=as.Date("2023-05-04"), y=1500, label = "C", size = 5) 
plot_5m
```

#save as jpeg (combined plot)

```{r}
jpeg("../Figures/Fig2.jpg", width = 8, height = 10, units="in", res=600)
plot_net / plot_1m / plot_5m 
```
