---
title: "qpcr_plots"
author: "Juliana Cornett"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#code to generate qPCR plots (Figure(s) __ in manuscript)

#install packages (ggplot2 & ggpubr for creating figures; dplyr and reshape2 for data manipulation, ggdist for violin plot)

```{r}
#install.packages("ggplot2")
#install.packages("ggpubr")
#install.packages("dplyr")
#install.packages("reshape2")
#install.packages("ggdist")
```

#load libraries

```{r}
library(ggplot2)
library(ggpubr)
library(dplyr)
library(reshape2)
library(ggdist)
```

#read in qPCR data 

```{r}
qpcr <- read.csv("../Data/Alexandrium_qPCR_Results.csv")
```

#reformat

```{r}
qpcr$Date <- as.Date(qpcr$Date, "%m/%d/%Y")
qpcr$Quantity_1 <- as.numeric(gsub(",", "", qpcr$Quantity_1))
qpcr$Quantity_2 <- as.numeric(gsub(",", "", qpcr$Quantity_2))
qpcr$Quantity_3 <- as.numeric(gsub(",", "", qpcr$Quantity_3))
qpcr$Quantity_Mean <- as.numeric(gsub(",", "", qpcr$Quantity_Mean))
```

#extract month 

```{r}
qpcr$Month <- format(as.Date(qpcr$Date, format="%d/%m/%Y"),"%b")
```

#palettes

```{r}
sunset_25 <- hcl.colors(25, palette = "Sunset")
```

```{r}
"#704D9E" "#7F4EA2" "#8D4FA5" "#9A51A7" "#A653A8" "#B156A9" "#BC5AA9" "#C65EA8" "#CF63A6" "#D868A3" "#E06EA0" "#E7759C" "#ED7C97" "#F18592" "#F48E8E" "#F6978A" "#F7A086" "#F9A983" "#F9B282" "#F9BB81" "#F9C483" "#F8CD86" "#F6D68A" "#F5DE91" "#F3E79A"
```

```{r}
sunset_5 <- hcl.colors(5, palette = "Sunset")
```

#scatterplot

```{r}
plot_qpcr_scatter <- ggplot(qpcr, aes(x = Date, y = Quantity_Mean)) +
  geom_point(aes(y = Quantity_Mean, fill = Month), size = 5, shape = 21) + 
  scale_fill_manual(values = sunset_5) +
  labs(y = "Quantity (copy number)") + 
  theme_pubr() +
  theme(legend.position = "right") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y")
plot_qpcr_scatter
```

#save as jpeg

```{r}
jpeg("../Figures/Fig4.jpg", width = 8, height = 5, units="in", res=600)
plot_qpcr_scatter
```

#raincloud plot

#read in microscope data

```{r}
count_micro <- read.csv("../Data/Alexandrium_MicroscopeCounts.csv")
```

```{r}
count_sub <- select(count_micro, c("ID_yyyymmdd", "Count_1m_L", "Count_5m_L"))
```

#gather into long form

```{r}
count_long <- melt(count_sub, id.vars = "ID_yyyymmdd", variable.name = "Method")
```

```{r}
ggplot(count_long, aes(x = factor(Method), y = value, fill = factor(Method))) +
  stat_halfeye(adjust = 0.5, justification = -0.2, .width = 0, point_colour = NA) +
  geom_boxplot(width = 0.12, outlier.color = NA, alpha = 0.5) +
  stat_dots(side = "left", justification = 1.1, binwidth = 25) +
  theme_pubr()
```

#save as jpeg


