---
title: "timeseries_plots"
author: "Juliana Cornett"
date: "2024-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## timeseries plots

#install packages

```{r}
#install.packages("tidyverse")
#install.packages("ggpubr")
#install.packages("patchwork")
#install.packages("NADA")
#install.packages("ggtext")
#install.packages("reshape2")
#install.packages("cowplot")
```

#load libraries

```{r}
library(tidyverse)
library(ggpubr)
library(patchwork)
library(NADA)
library(ggtext)
library(reshape2)
library(cowplot)
```

#read in data

```{r}
psts <- read.csv("../Data/Oyster_PSTs.csv")
alex <- read.csv("../Data/Alexandrium_MicroscopeCounts.csv")
qpcr <- read.csv("../Data/Alexandrium_qPCR_Results.csv")
```

#format 

```{r}
psts$Date <- as.Date(psts$Date, "%m/%d/%Y")
alex$Date <- as.Date(alex$Date, "%m/%d/%Y")
qpcr$Date <- as.Date(qpcr$Date, "%m/%d/%Y")
qpcr <- subset(qpcr, qpcr$Sample_Type == "Sample")
qpcr <- subset(qpcr, qpcr$Quantity_Corrected >= 63.98)
```

#psts timeseries

```{r}
pst_time <- ggplot(psts, aes(x = Date, y = Tox_ug_100g, fill = Method, shape = Method)) + 
  scale_fill_manual(values = c("black", "darkgray"), labels = c("MBA", "ELISA")) +
  scale_shape_manual(values = c(24, 21), labels = c("MBA", "ELISA")) +
  geom_point(size = 4, color = "black", alpha = 0.75) +
  theme_pubr() +
  theme(legend.position = "right") +
  labs(
    x = element_blank(),
    y = "PSTs (\u00b5g/100g)")  +
  geom_hline(yintercept = 80, linetype = "dashed") +
  geom_hline(yintercept = 34, linetype = "dotted")
pst_time
```

#save as jpeg

```{r}
jpeg("../New Figures/FigS3.jpg", width = 8, height = 5, units="in", res=600)
pst_time
```

#PST time series with imputed values for MBA < 34

```{r}
pst_mba <- subset(psts, Method == "DEC")

#apply ROS method for MBA <=34

pst_obs <- pst_mba$Tox_ug_100g
pst_censored <- pst_mba$Tox_ug_100g <= 34

#fit the ROS model

pst_order <- order(pst_mba$Tox_ug_100g, na.last = NA)
pst_ros <- ros(pst_mba$Tox_ug_100g[pst_order], pst_censored[pst_order])

#extract imputed values

pst_imputed <- pst_ros$modeled

#reorder imputed values based on original dataset order

pst_imputed_reordered <- pst_imputed[order(pst_order)]

#add ROS imputed values to dataframe

pst_mba$ROS_PST_MBA_ug_100g <- ifelse(pst_censored, pst_imputed_reordered, pst_mba$Tox_ug_100g)

#plot

psts_ros <- read.csv("../Data/Oyster_PSTs_ROS.csv")
psts_ros$Date <- as.Date(psts_ros$Date, "%m/%d/%Y")
pst_ros_time <- ggplot(psts_ros, aes(x = Date, y = Tox_ug_100g, fill = Method, shape = Method)) + 
  scale_fill_manual(values = c("black", "darkgray"), labels = c("MBA", "ELISA")) +
  scale_shape_manual(values = c(24, 21), labels = c("MBA", "ELISA")) +
  geom_point(size = 4, color = "black", alpha = 0.75) +
  theme_pubr() +
  theme(legend.position = "right") +
  labs(
    x = element_blank(),
    y = "PSTs (\u00b5g/100g)")  +
  geom_hline(yintercept = 80, linetype = "dashed") +
  geom_hline(yintercept = 34, linetype = "dotted")
pst_ros_time
```

#counts timeseries

#microscope timeseries (A) - one axis for cells (net) and one for cells/L (1m and 5m)

```{r}
counts_time <- ggplot(alex, aes(x=Date)) +
  
  geom_point(aes(y=Count_Net*50), fill = "white", shape = 21, size = 3, alpha = 0.75) + 
  geom_point(aes(y=Count_1m_L), fill = "darkgray", shape = 22, size = 3, alpha = 0.75) +
  geom_point(aes(y=Count_5m_L), fill = "black", shape = 25, size = 3, alpha = 0.75) +
  scale_y_continuous(
    name = "*A. catenella* Count at 1m or 5m (Cells/L)",
    sec.axis = sec_axis(~ . / 50, name = "*A. catenella* Count from Net Tow (Cells)")
  ) +
  theme_pubr() +
  labs(x = element_blank()) +
  theme(axis.title.y = ggtext::element_markdown(), axis.title.y.right = ggtext::element_markdown())
  
counts_time

#add legend for different methods

```

```{r}
alex
alex_long <- select(alex, c("Date", "Count_Net", "Count_1m_L", "Count_5m_L"))
alex_long <- melt(alex_long, id.vars = "Date", variable.name = "Method")
alex_long$Method <- as.character(alex_long$Method)
alex_long$Method[alex_long$Method=="Count_Net"] <- "Net"
alex_long$Method[alex_long$Method=="Count_1m_L"] <- "1m"
alex_long$Method[alex_long$Method=="Count_5m_L"] <- "5m"

counts_time_v2 <- ggplot(alex_long, aes(x=Date, y=value, fill = Method, shape = Method)) +
  geom_point(size = 3, alpha = 0.75) +
  scale_fill_manual(values = c("darkgray", "black", "white")) +
  scale_shape_manual(values = c(22, 25, 21)) +
  theme_pubr() +
  labs(x = element_blank()) +
  theme(legend.position = "right")

counts_time_v2

#extract legend

legend_methods <- get_legend(counts_time_v2)
legend_plot <- as_ggplot(legend_methods)
```

#final figure (with legend)

```{r}
counts_time_final <- ggdraw(counts_time) +
  draw_plot(
    {legend_methods
      },
    # The distance along a (0,1) x-axis to draw the left edge of the plot
    x = 0, 
    # The distance along a (0,1) y-axis to draw the bottom edge of the plot
    y = 0.7,
    # The width and height of the plot expressed as proportion of the entire ggdraw object
    width = 0.3, 
    height = 0.3) 

counts_time_final

jpeg("../New Figures/FigS1.jpg", width = 8, height = 5, units="in", res=600)
counts_time_final
```

#qpcr timeseries (B)

```{r}
qpcr_mean <- aggregate(Copies_L_Corrected ~ Date, data = qpcr, FUN = mean)
qpcr_mean$log_qpcr <- log(qpcr_mean$Copies_L_Corrected)
qpcr_time <- ggplot(qpcr_mean, aes(x = Date, y = log_qpcr)) + 
  geom_point(size = 4, color = "black", alpha = 0.75) + 
  theme_pubr() + 
  labs(x = element_blank(), y = "Mean Log-transformed *A. catenella* qPCR Quantity (Copies/L)") + theme(axis.title.y = ggtext::element_markdown())
 qpcr_time
```

#save as jpeg

```{r}
jpeg("../New Figures/FigS2.jpg", width = 8, height = 5, units="in", res=600)
qpcr_time
```
